# config.yaml

modbus:
  address: "localhost:502" # Modbus server address and port
  slaveID: 1 # Slave ID (Unit ID)

polling_interval_seconds: 3 # Polling interval in seconds

data_points:
  - register: 001 # Modbus register address
    name: "room_temperature" # Label for the data point and prometheus metric name
    type: "gauge" # prometheus metric type
    format: "float32" # Display format (e.g., int, float32, float64)
  - register: 3
    name: "temperature_seconds"
    type: "histogram"
    format: "float32"

http_server:
  port: 2112 # Prometheus server port
